config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :messages do
    member do
      post :send_email
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "topics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  has_rich_text :content
  has_many_attached :attachments

  validates :from, presence: true
  validates :to, presence: true

  belongs_to :topic, touch: true
  belongs_to :reply_to, optional: true, class_name: 'Message'
  has_many :replies, class_name: 'Message', foreign_key: :reply_to_id, dependent: :nullify

  before_validation :build_or_find_topic, if: -> { topic.blank? }

  scope :latest_first, -> { order(created_at: :desc) }

  after_create_commit -> { broadcast_prepend_to topic }
  after_update_commit -> { broadcast_replace_to topic }
  after_destroy_commit -> { broadcast_remove_to topic }

  def build_or_find_topic
    if reply_to.present?
      self.topic = reply_to.topic
    else
      build_topic(subject: subject)
    end
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :messages, dependent: :destroy

  def attachments
    messages.map { |message| (message.attachments + message.content.embeds) }.flatten
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ send_email show edit update destroy ]

  # GET /messages
  def index
    @messages = Message.all
  end

  # GET /messages/1
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new

    if params[:reply_to_id].present?
      reply_to = Message.find(params[:reply_to_id])
      @message.reply_to = reply_to # we also have to save reference to original Message
      @message.subject = "Re: #{reply_to.subject}"
      @message.to = reply_to.from
      @message.from = reply_to.to
      @message.cc = reply_to.cc
    end
  end

  def send_email
    MessageMailer.with(message: @message).send_message.deliver_now

    redirect_back fallback_location: messages_url, notice: 'Message was send.'
  end

  # POST /messages
  def create
    @message = Message.new(message_params)

    if @message.save
      email = MessageMailer.with(message: @message).send_message.deliver_now
      @message.update!(message_id: email.message_id)
      redirect_to @message, notice: "Message was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /messages/1
  def destroy
    @message.destroy
    redirect_to messages_url, notice: "Message was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:subject, :from, :to, :cc, :bcc, :content, :reply_to_id, attachments: [])
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      redirect_to @topic, notice: "Topic was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /topics/1
  def update
    if @topic.update(topic_params)
      redirect_to @topic, notice: "Topic was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /topics/1
  def destroy
    @topic.destroy
    redirect_to topics_url, notice: "Topic was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:subject)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotmailing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-200">
    <main class="container max-w-screen-lg mx-auto m-5 px-5">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, class: "contents") do |form| %>
  <%= form.hidden_field :reply_to_id %>

  <% if message.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :subject %>
    <%= form.text_field :subject, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :from %>
    <%= form.text_field :from, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :to %>
    <%= form.text_field :to, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cc %>
    <%= form.text_field :cc, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :bcc %>
    <%= form.text_field :bcc, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.rich_text_area :content, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :attachments %>
    <%= form.file_field :attachments, multiple: true, direct_upload: true %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="container mx-auto" id="<%= dom_id message %>">
  <div class="relative mt-5 mb-5 sm:items-center mx-auto">
    <div class="rounded-md drop-shadow bg-white p-2">
      <div class="border-b-2 py-4 px-10 mb-4 ">
        <h2 class="font-medium title-font text-gray-900 mb-1 text-xl"><%= message.from %></h2>
        <div class="flex justify-between">
          <p class="leading-relaxed text-gray-500">to: <%= message.to %></p>
          <p class="leading-relaxed text-gray-500 object-right"><%= message.created_at %></p>
        </div>
        <% (message.attachments + message.content.embeds).each do |attachment| %>
          <%= link_to rails_blob_url(attachment.blob), download: true, class: "bg-gray-100 inline-flex py-1 px-1 rounded-lg items-center hover:bg-gray-200 border" do %>
            <span class="leading-none">
              <span class="title-font font-medium text-xs"><%= attachment.blob.filename %></span>
            </span>
          <% end %>
        <% end %>
      </div>

      <div class="px-10">
        <%= message.content %>
      </div>

      <% if message.attachments.any? || message.content.embeds.any? %>
        <div class="px-10 inline-flex gap-1 mt-4">
          <% (message.attachments + message.content.embeds).each do |attachment| %>
            <% blob = attachment.blob %>
            <div class="bg-white p-1 rounded-lg bg-gray-100 hover:bg-gray-200 border relative w-40 h-40">
            <%= link_to rails_blob_url(blob), download: true, class: 'text-center' do %>
              <% if blob.representable? %>
                <%= image_tag blob.representation(resize_to_limit: [ 100, 100 ]), class: 'mx-auto' %>
              <% else %>
                <p class="text-blue-600 text-center text-8xl mx-auto">
                  <%= fa_icon 'file' %>
                </p>
              <% end %>
              <div class="mt-2 absolute inset-x-0 bottom-0">
                <p class="whitespace-nowrap title-font font-medium text-xs"><%= blob.filename.to_s.truncate(20) %></p>
                <p class="whitespace-nowrap title-font text-xs"><%= number_to_human_size(blob.byte_size) %></p>
              </div>
            <% end %>
            </div>
          <% end %>
        </div>
      <% end %>

      <div class="text-end text-right">
        <div class="inline-block ml-2">
          <%= button_to 'Send Again', send_email_message_path(message), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        </div>
        <div class="inline-block ml-2">
          <%= link_to 'Reply', new_message_path(reply_to_id: message.id), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium", target: '_top' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/messages/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing message</h1>

  <%= render "form", message: @message %>

  <%= link_to "Show this message", @message, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to messages", messages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/messages/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Messages</h1>
    <%= link_to 'New message', new_message_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="messages" class="min-w-full">
    <%= render @messages %>
  </div>
</div>

app/views/messages/new.html.erb
<div class="mx-auto">
  <div class="rounded-md drop-shadow bg-white p-10">
  <h1 class="text-lg font-bold text-4xl">New message</h1>

  <%= render "form", message: @message %>

  <%= link_to 'Cancel', topics_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/messages/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @message %>

    <%= button_to "Send again", send_email_message_path(@message), method: :post, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this message', edit_message_path(@message), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this message', message_path(@message), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to messages', messages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/topics/_form.html.erb
<%= form_with(model: topic, class: "contents") do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :subject %>
    <%= form.text_field :subject, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div class="topic-list" id="<%= dom_id(topic) %>">
  <%= link_to topic do %>
    <div class="flex justify-between">
      <p class="title-font text-2xl font-bold"><%= topic.subject %></p>
      <p class="leading-relaxed text-gray-500 pt-1"><%= topic.messages.last.created_at %></p>
    </div>
  <% end %>
  <div class="flex justify-between">
    <p class="leading-relaxed text-gray-500 pt-1"><%= topic.messages.last.from %></p>
    <div class="py-1 text-right">
        <% topic.attachments.each do |attachment| %>
          <%= link_to rails_blob_url(attachment.blob), download: true, class: "bg-gray-100 inline-flex py-1 px-1 rounded-lg items-center hover:bg-gray-200 border" do %>
            <span class="leading-none">
              <span class="title-font font-medium text-xs"><%= attachment.blob.filename %></span>
            </span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing topic</h1>

  <%= render "form", topic: @topic %>

  <%= link_to "Show this topic", @topic, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to topics", topics_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/topics/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="h1-main">Inbox</h1>
    <%= link_to 'New message', new_message_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="topics" class="min-w-full">
    <%= turbo_stream_from :topics %>
    <%= turbo_frame_tag :topics , target: '_top' do %>
      <%= render @topics %>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New topic</h1>

  <%= render "form", topic: @topic %>

  <%= link_to 'Back to topics', topics_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/topics/show.html.erb
<div class="w-full">
  <%= turbo_stream_from @topic %>
  <%= turbo_frame_tag @topic, target: '_top' do %>
    <div class="flex justify-between items-center mb-5">
      <h1 class="h1-main"><%= @topic.subject %></h1>
      <%= link_to 'Inbox', topics_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>

    <%= turbo_frame_tag :messages do %>
      <% @topic.messages.latest_first.each do |message| %>
        <%= render message %>
      <% end %>
    <% end %>

    <div class="inline-block ml-2">
      <%= button_to 'Destroy this topic', topic_path(@topic), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to topics', topics_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <% end %>
</div>